baseurl: "/"
languageCode: "en-US"
title: "J Song's Blog"
theme: "hugo-paged"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "‚Ü©"
author: 'J Song'

outputs:
  home: [html, rss, json]

menu:
  main:
    - identifier: search
      name: üîçsearch
      url: search
      weight: 1
    - identifier: home
      name: Home
      url: /
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: tech
      name: Tech
      url: /Tech/
      weight: 5
    - identifier: reading
      name: Reading
      url: /Reading/
      weight: 6

params:
  description: " ^-^ "
  logo:
    main:
      alt: LOGO TEXT
      img: "/images/logo.png"
  footer: "&copy; [J Song](https://jennysong924.github.io) {Year}"
  # twitterImage: "/images/logo.png"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true